//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhn.Git.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nhn.Git.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap _return {
            get {
                object obj = ResourceManager.GetObject("_return", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Cancel to cancel this OnApply.  OK to continue.
        /// </summary>
        public static string ApplyProviderOptions {
            get {
                return ResourceManager.GetString("ApplyProviderOptions", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Branch {
            get {
                object obj = ResourceManager.GetObject("Icon_Branch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Branch1 {
            get {
                object obj = ResourceManager.GetObject("Icon_Branch1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Button_Search {
            get {
                object obj = ResourceManager.GetObject("Icon_Button_Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Button_Swtich {
            get {
                object obj = ResourceManager.GetObject("Icon_Button_Swtich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Change_A {
            get {
                object obj = ResourceManager.GetObject("Icon_Change_A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Change_C {
            get {
                object obj = ResourceManager.GetObject("Icon_Change_C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Change_D {
            get {
                object obj = ResourceManager.GetObject("Icon_Change_D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Change_M {
            get {
                object obj = ResourceManager.GetObject("Icon_Change_M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Change_R {
            get {
                object obj = ResourceManager.GetObject("Icon_Change_R", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Change_T {
            get {
                object obj = ResourceManager.GetObject("Icon_Change_T", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Change_U {
            get {
                object obj = ResourceManager.GetObject("Icon_Change_U", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Change_X {
            get {
                object obj = ResourceManager.GetObject("Icon_Change_X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Child {
            get {
                object obj = ResourceManager.GetObject("Icon_Child", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Father {
            get {
                object obj = ResourceManager.GetObject("Icon_Father", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Repo {
            get {
                object obj = ResourceManager.GetObject("Icon_Repo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_state_1 {
            get {
                object obj = ResourceManager.GetObject("Icon_state_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_state_2 {
            get {
                object obj = ResourceManager.GetObject("Icon_state_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_state_3 {
            get {
                object obj = ResourceManager.GetObject("Icon_state_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_state_4 {
            get {
                object obj = ResourceManager.GetObject("Icon_state_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_State_Add {
            get {
                object obj = ResourceManager.GetObject("Icon_State_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_State_Commit {
            get {
                object obj = ResourceManager.GetObject("Icon_State_Commit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_State_Mix {
            get {
                object obj = ResourceManager.GetObject("Icon_State_Mix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_State_Repo {
            get {
                object obj = ResourceManager.GetObject("Icon_State_Repo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Tag {
            get {
                object obj = ResourceManager.GetObject("Icon_Tag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_Tracking {
            get {
                object obj = ResourceManager.GetObject("Icon_Tracking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Icon_URL1 {
            get {
                object obj = ResourceManager.GetObject("Icon_URL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon Icon400 {
            get {
                object obj = ResourceManager.GetObject("Icon400", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Images_32bit {
            get {
                object obj = ResourceManager.GetObject("Images_32bit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IsTracking {
            get {
                object obj = ResourceManager.GetObject("IsTracking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Source Code Control Provider.
        /// </summary>
        public static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} you are trying to edit is read only on disk. Do you want do make the file writable so you can continue editing it?.
        /// </summary>
        public static string QEQS_EditUncontrolledReadOnly {
            get {
                return ResourceManager.GetString("QEQS_EditUncontrolledReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked in.
        /// </summary>
        public static string Status_CheckedIn {
            get {
                return ResourceManager.GetString("Status_CheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked out by you.
        /// </summary>
        public static string Status_CheckedOut {
            get {
                return ResourceManager.GetString("Status_CheckedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending add.
        /// </summary>
        public static string Status_PendingAdd {
            get {
                return ResourceManager.GetString("Status_PendingAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify,None,Checked.
        /// </summary>
        public static string STATUS_SZ_CHECKIN_MODIFIED {
            get {
                return ResourceManager.GetString("STATUS_SZ_CHECKIN_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict Status.
        /// </summary>
        public static string STATUS_SZ_CONFLICT {
            get {
                return ResourceManager.GetString("STATUS_SZ_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete,Staged,Checked.
        /// </summary>
        public static string STATUS_SZ_DELETE {
            get {
                return ResourceManager.GetString("STATUS_SZ_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Status.
        /// </summary>
        public static string STATUS_SZ_IGNORED {
            get {
                return ResourceManager.GetString("STATUS_SZ_IGNORED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify,Staged,Checked.
        /// </summary>
        public static string STATUS_SZ_MODI_STAGED_MODI {
            get {
                return ResourceManager.GetString("STATUS_SZ_MODI_STAGED_MODI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None,Staged,Checked.
        /// </summary>
        public static string STATUS_SZ_MODIFY_STAGED {
            get {
                return ResourceManager.GetString("STATUS_SZ_MODIFY_STAGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None,Noen,Checked.
        /// </summary>
        public static string STATUS_SZ_NEW_CHECKIN {
            get {
                return ResourceManager.GetString("STATUS_SZ_NEW_CHECKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None,Staged,UnChecked.
        /// </summary>
        public static string STATUS_SZ_NEW_STAGED {
            get {
                return ResourceManager.GetString("STATUS_SZ_NEW_STAGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Controlled.
        /// </summary>
        public static string STATUS_SZ_NOT_CONTROLLED {
            get {
                return ResourceManager.GetString("STATUS_SZ_NOT_CONTROLLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown Status.
        /// </summary>
        public static string STATUS_SZ_NULL {
            get {
                return ResourceManager.GetString("STATUS_SZ_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Status.
        /// </summary>
        public static string STATUS_SZ_RENMAE {
            get {
                return ResourceManager.GetString("STATUS_SZ_RENMAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify,Staged,UnChecked.
        /// </summary>
        public static string STATUS_SZ_STAGE_MODIFIED {
            get {
                return ResourceManager.GetString("STATUS_SZ_STAGE_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHN Git Property Window.
        /// </summary>
        public static string ToolWindowCaption {
            get {
                return ResourceManager.GetString("ToolWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} you are going to delete is a source controlled file. Are you sure you want to continue and delete this file?.
        /// </summary>
        public static string TPD_DeleteControlledFile {
            get {
                return ResourceManager.GetString("TPD_DeleteControlledFile", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap VsBar500 {
            get {
                object obj = ResourceManager.GetObject("VsBar500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap VsIcon501 {
            get {
                object obj = ResourceManager.GetObject("VsIcon501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap waiting {
            get {
                object obj = ResourceManager.GetObject("waiting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
